# Generated by Django 5.0 on 2025-07-06 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed_app', '0002_post_seenpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelevanceWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name for this weight configuration', max_length=100, unique=True)),
                ('primary_tag_weight', models.FloatField(default=1.0, help_text='Weight for posts matching primary interests')),
                ('secondary_tag_weight', models.FloatField(default=0.5, help_text='Weight for posts matching secondary interests')),
                ('freshness_weight', models.FloatField(default=0.3, help_text='Weight for post freshness (newer posts get higher scores)')),
                ('seen_penalty', models.FloatField(default=0.1, help_text='Penalty multiplier for posts already seen by user')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this configuration is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_active', '-created_at'],
            },
        ),
    ]
